In [2]:
 # Copyright (c) 2019 Skymind AI Bhd.
# Copyright (c) 2020 CertifAI Sdn. Bhd.
#
# This program and the accompanying materials are made available under the
# terms of the Apache License, Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0.
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# SPDX-License-Identifier: Apache-2.0

# NumPy Quickstart 

We will use the **NumPy** module to create and apply mathematical operations on matrices (additional, substraction).

In [3]:
import numpy as np

Create a simple array of integers

In [4]:
array_1d = np.arange(0, 10)

The function `arange` creates an array from `range(0,10)`. The `arange()` function is similar to that of Python's `range()`.

In [5]:
array_1d 
#row vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Other way to print array_1d

In [6]:
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


Create a $2\times2$ matrix. (2-dimensional array)

In [7]:
array_2d = np.array([[1, 2], [3, 4]])

In [8]:
array_2d

array([[1, 2],
       [3, 4]])

Create a $3\times 3$ matrix.

In [9]:
array_3d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [10]:
array_3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Perform addition of two $3\times 3$ matrices. Must same shape.

In [11]:
matrixA = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [12]:
print(np.add(matrixA,matrixB))

[[2 2 2]
 [2 2 2]
 [2 2 2]]


Perform subtraction of two $3\times 3$ matrices.

In [13]:
matrixA = np.array([[2, 2, 2], [2, 2, 2], [2, 2, 2]])
matrixB = np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])

In [14]:
print(np.subtract(matrixA, matrixB))

[[1 1 1]
 [1 1 1]
 [1 1 1]]


Perform a Dot Product between 2 matrices.

Remember the rule that the matrix product of a matrix $A$ of shape $m \times n$ with a matrix $B$ of shape $n \times o$ has shape $m \times o$. 

In [15]:
print(np.matmul(matrixA, matrixB))

[[6 6 6]
 [6 6 6]
 [6 6 6]]


The dot product of a $3\times 3$ matrix with a $3\times 2$ matric is a $3\times 2$ matrix.

Generate a $3\times 3$ matrix with all zeros.

In [16]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Generate a $3\times 3$ matrix with all ones.

In [17]:
ones = np.ones((3, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3D tensor.

In [18]:
tensor_3d = np.array([[[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]],
                      [[1, 1, 1, 1],
                       [1, 1, 1, 1],
                       [1, 1, 1, 1]]
                     ])

In [19]:
tensor_3d

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [20]:
tensor_3d.shape

(2, 3, 4)

The shape of the tensor is described as **Width * Rows * Columns**.

Below is an example of a 4-dimension tensor, or a tensor of `rank 4`.

In [21]:
tensor_4 = np.array([[[[1,2,3,7],
                       [1,3,5,0],
                       [2,3,4,4]],
                      [[2,3,4,6],
                       [6,3,4,8],
                       [4,6,0,7]]],
                     [[[1,2,6,9],
                       [2,3,4,3],
                       [7,4,4,3]],
                      [[2,6,4,3],
                       [7,3,4,2],
                       [8,5,6,8]]]])

Using the `shape` attribute, we can see the magnitude of dimensions of said tensor.<br><br>
A $n$-dimension tensor will display a number of $n$ magnitudes. We can also use `ndim` to show the rank(dimension) of the tensor.

In [22]:
print(tensor_4.shape)
print(tensor_4.ndim)

(2, 2, 3, 4)
4


## Common functions to operate on NumPy arrays

In [23]:
array_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_3x3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Check the shape of the array `array_3x3`.

In [24]:
array_3x3.shape

(3, 3)

Flatten `array_3x3`. Flatten will reduce any array of any dimensions into a 1-dimension array.

In [25]:
flattened_arr = array_3x3.ravel()

In [26]:
flattened_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
flattened_arr.shape

(9,)

**Use the `.copy()` method to clone the matrix instead of doing a reference.**


In [28]:
matrixA = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
matrixA

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`matrixB` is a reference to `matrixA`.`matrixC` is a copy of `matrixA`.

In [29]:
matrixB = matrixA 
matrixB

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
matrixC = np.copy(matrixA)

In [31]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Change the first row of matrixA

In [32]:
matrixA[0] = [99, 99, 99]

In [33]:
matrixA

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

matrixB has declare same as matrixA. So when value of matrixA changed, value of matrixB also will changed. 

In [34]:
matrixB

array([[99, 99, 99],
       [ 4,  5,  6],
       [ 7,  8,  9]])

matrixC use the copy function, thus the value of matrixC is not changed. 

In [35]:
matrixC

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Note that when we modify `matrixA`, `matrixB` changes, but not `matrixC`

## Array Manipulation

**Perform vertical (menegak) stack for 2 matrices using `numpy.vstack`.**

Declare 3x3, with 0 values inside.

In [36]:
matrixA = np.zeros((3, 3))
matrixA

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [37]:
matrixB = np.ones((3, 3))
matrixB

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
vstack_matrix = np.vstack((matrixA, matrixB))
vstack_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [39]:
vstack_matrix.shape

(6, 3)

**Perform horizontal stack for 2 matrices using `numpy.hstack`.**

In [40]:
hstack_matrix = np.hstack((matrixA, matrixB))
hstack_matrix

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [41]:
hstack_matrix.shape

(3, 6)

**Perform depth stack for 2 matrices using `numpy.dstack`.**

In [62]:
matrixD = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrixE = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

In [66]:
matrixD

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
matrixE

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [67]:
dstack_matrix = np.dstack((matrixD, matrixE))
dstack_matrix

array([[[ 1, 10],
        [ 2, 20],
        [ 3, 30]],

       [[ 4, 40],
        [ 5, 50],
        [ 6, 60]],

       [[ 7, 70],
        [ 8, 80],
        [ 9, 90]]])

In [44]:
dstack_matrix.shape

(3, 3, 2)

**Transpose a matrix.**

In [70]:
matrixF = np.transpose(matrixD)
matrixF

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

**Reshape a matrix into the assigned row x column.**

In [71]:
matrixF = matrixD.reshape(1, 9)
matrixF

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

**Split a matrix vertically at the n-th index to 2 equal-sized subarrays.**

In [73]:
matrixD = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixD

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [74]:
matrixF = np.vsplit(matrixD, 2)
matrixF

[array([[0, 0, 0],
        [0, 0, 0]]), array([[1, 1, 1],
        [1, 1, 1]])]

**Split a matrix horizontally into 3 equal-sized subarrays.** 

In [49]:
matrixA = np.array([[0, 0, 0], [0, 0, 0], [1, 1, 1], [1, 1, 1]])
matrixA

array([[0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1]])

In [50]:
matrixC = np.hsplit(matrixA, 3)
matrixC

[array([[0],
        [0],
        [1],
        [1]]), array([[0],
        [0],
        [1],
        [1]]), array([[0],
        [0],
        [1],
        [1]])]

## Exercise

Create a $5\times 3$ matrix populated with random samples from a uniform distribution and name it **`mat_1`**.

*hint: `numpy.random.rand`*

In [51]:
mat_1 = np.random.rand(5, 3)
mat_1

array([[0.83367275, 0.79111421, 0.18234297],
       [0.33774929, 0.91131853, 0.34707482],
       [0.55183786, 0.75737953, 0.82019757],
       [0.96442745, 0.74410621, 0.77595043],
       [0.08606538, 0.75189041, 0.33701298]])

Create a matrix **`mat_2`** of any size. The matrix should be eligible to perform matrix multiplication with `mat_1`.

In [52]:
mat_2 = np.random.rand(3, 2)
mat_2

array([[0.70001244, 0.58972124],
       [0.00856082, 0.27114881],
       [0.79634444, 0.85369731]])

Perform matrix multiplication of `mat_1` and `mat_2` and store it in variable **`mat_3`**.

In [53]:
mat_3 = np.matmul(mat_1, mat_2)
mat_3

array([[0.73556169, 0.8618099 ],
       [0.52062144, 0.7425777 ],
       [1.04593693, 1.23099352],
       [1.29940518, 1.43293365],
       [0.33506204, 0.54233584]])

Create another matrix that has the same number of columns as `mat_3` and name it **`mat_4`**

In [54]:
mat_4 = np.random.rand(3, 2)
mat_4

array([[0.77386403, 0.20132717],
       [0.2840089 , 0.67223133],
       [0.24474665, 0.92668179]])

Stack matrix `mat_3` and `mat_4` vertically. Name the result **`mat_5`**.

In [55]:
mat_5 = np.vstack((mat_3, mat_4))
mat_5

array([[0.73556169, 0.8618099 ],
       [0.52062144, 0.7425777 ],
       [1.04593693, 1.23099352],
       [1.29940518, 1.43293365],
       [0.33506204, 0.54233584],
       [0.77386403, 0.20132717],
       [0.2840089 , 0.67223133],
       [0.24474665, 0.92668179]])

Transpose `mat_5` and name the transposed matrix **`mat_6`**.

In [56]:
mat_6 = np.transpose(mat_5)
mat_6

array([[0.73556169, 0.52062144, 1.04593693, 1.29940518, 0.33506204,
        0.77386403, 0.2840089 , 0.24474665],
       [0.8618099 , 0.7425777 , 1.23099352, 1.43293365, 0.54233584,
        0.20132717, 0.67223133, 0.92668179]])

Check the shape of **`mat_6`**.

In [57]:
mat_6.shape

(2, 8)

Vertically split **`mat_6`** into two subarrays.

In [58]:
arr = np.vsplit(mat_6,2)
arr

[array([[0.73556169, 0.52062144, 1.04593693, 1.29940518, 0.33506204,
         0.77386403, 0.2840089 , 0.24474665]]),
 array([[0.8618099 , 0.7425777 , 1.23099352, 1.43293365, 0.54233584,
         0.20132717, 0.67223133, 0.92668179]])]